DeviceTrackingSystem/Models/Patient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string Patient_ID { get; set; }
        public string IRFID { get; set; }
        public string IRFName { get; set; }
        public int Customer_ID { get; set; }

        public string Customer_Name { get; set; }

         [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Implant_Date { get; set; }
        public string Implant_Physcian { get; set; }
        public Nullable<System.DateTime> Explant_Date { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}

DeviceTrackingSystem/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAcessLayer;
using System.Data.SqlClient;
using System.Data;
using System.Web.UI.WebControls;
using System.Web.Security;
using DeviceTrackingSystem.Models;
using System.Net;
using WebMatrix.WebData;

namespace DeviceTrackingSystem.Controllers
{
    public class PatientsController : Controller
    {
        DeviceTrackingEntities db = new DeviceTrackingEntities();
        DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
        //
        // GET: /Patients/
        [HttpGet]
        [Authorize]
        public ActionResult PatientsIndex(string paging)
        {
            if (!String.IsNullOrEmpty(paging))
            {
                ViewBag.rowsPerPage = int.Parse(paging);
            }
            else
            {
                // default value
                ViewBag.rowsPerPage = 20;
            }
            DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
            List<DeviceAccess> lstPatients = deviceDataAcessLayer.PatientDevice.ToList();

            if (HttpContext.Request.QueryString.Count == 0 || HttpContext.Request.QueryString.Count > 0)
            {
                string showAll = string.Empty;
                if (HttpContext.Request.QueryString["ShowAll"] != null)
                    showAll = HttpContext.Request.QueryString["ShowAll"].ToString().Trim();
                if (showAll == "true")
                {
                    lstPatients = deviceDataAcessLayer.PatientDevice.ToList();
                }
                else
                {
                    lstPatients = deviceDataAcessLayer.PatientDevice.Where(p => p.PatientsDeathDate == "-").ToList();
                }
            }

            if (HttpContext.Request.QueryString.Count > 0)
            {
                string SearchKey = string.Empty;
                if (HttpContext.Request.QueryString["SearchKey"] != null)
                    SearchKey = HttpContext.Request.QueryString["SearchKey"].ToString().Trim();
                string ParentSearchKey = string.Empty;
                if (HttpContext.Request.QueryString["ParentSearchKey"] != null)
                    ParentSearchKey = HttpContext.Request.QueryString["ParentSearchKey"].ToString().Trim();
                string ParentKey = string.Empty;
                if (HttpContext.Request.QueryString["ParentKey"] != null)
                    ParentKey = HttpContext.Request.QueryString["ParentKey"].ToString().Trim();

                if (!string.IsNullOrEmpty(SearchKey) && string.IsNullOrEmpty(ParentSearchKey) && string.IsNullOrEmpty(ParentKey))
                {
                    lstPatients = lstPatients.Where(i => i.PatientID.Contains(SearchKey)).ToList();
                }
                else if (string.IsNullOrEmpty(SearchKey) && !string.IsNullOrEmpty(ParentSearchKey) && string.IsNullOrEmpty(ParentKey))
                {
                    lstPatients = lstPatients.Where(i => i.Customer_Name.Contains(ParentSearchKey)).ToList();
                }
                else if (string.IsNullOrEmpty(SearchKey) && string.IsNullOrEmpty(ParentSearchKey) && !string.IsNullOrEmpty(ParentKey))
                {
                    lstPatients = lstPatients.Where(i => i.PatientsImplantDate.ToString().Contains(ParentKey)).ToList();
                }
                else if (!string.IsNullOrEmpty(SearchKey) && !string.IsNullOrEmpty(ParentSearchKey) && string.IsNullOrEmpty(ParentKey))
                {
                    lstPatients = lstPatients.Where(i => i.PatientID.Contains(SearchKey) && i.Customer_Name.Contains(ParentSearchKey)).ToList();
                }
                else if (!string.IsNullOrEmpty(SearchKey) && !string.IsNullOrEmpty(ParentSearchKey) && !string.IsNullOrEmpty(ParentKey))
                {
                    lstPatients = lstPatients.Where(i => i.PatientID.Contains(SearchKey) && i.Customer_Name.Contains(SearchKey) && i.PatientsImplantDate.ToString().Contains(ParentKey)).ToList();
                }
            }
            return View(lstPatients);
        }

        //
        // GET: /Patients/Details/5
        //[Authorize]
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        public ActionResult Details(int id = 0, string CustId = "")
        {
            DataAcessLayer.DeviceAccess.ViewModelPateintDetails PateintsModel = new DataAcessLayer.DeviceAccess.ViewModelPateintDetails();
            PateintsModel.PatientsDetails = deviceLayer.ParentPatientDetail().Where(p => p.ID == id).ToList();
            PateintsModel.SFAccountsDetails = deviceLayer.ChildPatientDetail().Where(p => p.Patient_ID == id && p.Customer_ID == CustId).ToList();
            return View(PateintsModel);
        }

        //
        // GET: /Patients/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Patients/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Patients/Edit/5
        [Authorize(Roles = "ReadWrite")]
        public ActionResult Edit(int id = 0, int CustId = 0)
        {
            Patient patient = new Patient();
            DeviceAccess deviceAccess = new DeviceAccess();
         
            ViewBag.id = id;
            ViewBag.CustId = CustId;
            try
            {
                patient = db.Patients.Find(id);
                if (patient == null)
                {
                    return HttpNotFound();
                }                          
               
                ViewBag.customerName = new SelectList(db.Customers, "ID", "Customer_Name", CustId);
                


            }
            catch (Exception ex)
            {

            }

            return View(patient);
        }

        //
        // POST: /Patients/Edit/5
        [Authorize(Roles = "ReadWrite")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                string ImplantDate = Request.Form["Implant_Date"];
                string ImplantPhyscian = Request.Form["Implant_Physcian"];
                string ExplantDate = Request.Form["Explant_Date"];
                int CustomerID = Convert.ToInt32(Request.Form["Customer_ID"]);
                var updatedby = User.Identity.Name;


                if (ModelState.IsValid)
                {
                    DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
                    bool isUpdated = deviceLayer.SavePatients(CustomerID, ImplantDate, ImplantPhyscian, ExplantDate, id, updatedby);
                    if (isUpdated)
                    {
                        TempData["message"] = "Record Successfully Updated";
                        return RedirectToAction("PatientsIndex");
                    }
                    {
                        TempData["message"] = "Error Occured!!";
                        return RedirectToAction("PatientsIndex");
                    }

                }
                return RedirectToAction("PatientsIndex");

            }
            catch
            {
                return View();
            }
        }
        [Authorize]
        //
        // GET: /Patients/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        [Authorize(Roles = "ReadWrite")]
        public ActionResult DeletePatientRecord(int id)
        {
            if (ModelState.IsValid)
            {
                DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
                var updatedby = User.Identity.Name;
                bool IsDeleted = deviceLayer.DeletePatientRecord(id, updatedby);
                if (IsDeleted)
                {
                    TempData["message"] = "Record Successfully Deleted";
                }
                return RedirectToAction("PatientsIndex");
            }
            return View();
        }
        //
        // POST: /Patients/Delete/5      
        [HttpPost]
        [Authorize(Roles = "ReadWrite")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [Authorize(Roles = "ReadWrite")]
        public ActionResult PatientDetailsEdit(int id = 0, string CustId = "", int DeviceId = 0, int patientId = 0)
        {
            List<DataAcessLayer.DeviceAccess.PatientsAssignedDevices> objsFAccountsDetails = new List<DataAcessLayer.DeviceAccess.PatientsAssignedDevices>();
            ViewBag.id = id;
            try
            {
                objsFAccountsDetails = deviceLayer.ChildPatientDetail();
                ViewBag.partId = new SelectList(deviceLayer.ChildPatientDetail(), "ID", "Part_ID", id);
                ViewBag.serialNumber = new SelectList(deviceLayer.ChildPatientDetail(), "ID", "Serial_Number", id);
                ViewBag.status = new SelectList(deviceLayer.ChildPatientDetail(), "ID", "Status", id);
                ViewBag.parentPartID = new SelectList(deviceLayer.ChildPatientDetail(), "ID", "ParentPartID", id);
                ViewBag.parentSerialNumber = new SelectList(deviceLayer.ChildPatientDetail(), "ID", "Parent_Serial_Number", id);
                ViewBag.custID = CustId.ToString();
                // ViewBag.ID = id;
                ViewBag.id = id;
                ViewBag.patientId = patientId;

DeviceTrackingSystem/Views/Patients/Details.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelPateintDetails


<h2>Details</h2>

<div style="padding-left:750px" id="divMessage">
    <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
</script>

@foreach (var item in Model.PatientsDetails)
{
    <p style="font-size:19px">Patient: @item.Patient_ID</p>
    <hr />
    <table>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">Customer : </td>
            <td>@item.Customer_Name</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">IRF : </td>
            <td>@item.PatientsImplantPhysician</td>


        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">Implant Date : </td>
            <td>@item.PatientsImplantDate</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">Updated :</td>
            <td>@item.Updated</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">Last Altered By :</td>
            <td>@item.Last_Altered_By</td>
        </tr>
    </table>

}
@if (Model.SFAccountsDetails.Count > 0)
{
<p style="padding-top:25px">
    <h2>Assigned Devices</h2>

    <hr />

</p>

<table class="table table-striped">
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">Part ID</td>
        <td align="right" style="font-weight:700; font-size:16px">Serial Number</td>
        <td align="right" style="font-weight:700; font-size:16px">Status</td>
        <td align="right" style="font-weight:700; font-size:16px">ParentPartID</td>
        <td align="right" style="font-weight:700; font-size:16px">Parent_Serial_Number</td>
        <td align="right" style="font-weight:700; font-size:16px">Action</td>
    </tr>
  
        @foreach (var item in Model.SFAccountsDetails)
        {
            <tr>
                <td>@item.Part_ID</td>
                <td>@item.Serial_Number</td>
                <td>@item.Status</td>
                <td>@item.ParentPartID</td>
                <td>@item.Parent_Serial_Number</td>
                <td>
                  
                    @Html.ActionLink("Edit", "Edit", "Device", new { id = item.ID, CustId = item.Customer_ID, DeviceLocId = item.DeviceLocID, Status = item.Status, ParentID = item.ParentPartID, Pid = item.PID }, new { target = "_blank" }) |
|
                   

                    @Html.ActionLink("Details", "Details", "Device", new { id = item.ID }, new { target = "_blank" })
                </td>
            </tr>
        }
           
</table>
}
else
{
    <hr />
    <div style="padding-left:400px; padding-top:20px; padding-bottom:20px">
        <h3>No devices Assigned for this patient</h3>
    </div>
    <hr />

}
@*<div id="GrandChildPatients"  hidden="hidden" >
    <table class="table table-striped">
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">Part ID</td>
            <td align="right" style="font-weight:700; font-size:16px">Serial Number</td>
            <td align="right" style="font-weight:700; font-size:16px">Status</td>
            <td align="right" style="font-weight:700; font-size:16px">ParentPartID</td>
            <td align="right" style="font-weight:700; font-size:16px">Parent_Serial_Number</td>
            <td align="right" style="font-weight:700; font-size:16px">Action</td>
        </tr>
        <tr>
            @foreach (var item in Model.SFAccountsDetails)
            {
                <td>@item.Part_ID</td>
                <td>@item.Serial_Number</td>
                <td>@item.Status</td>
                <td>@item.ParentPartID</td>
                <td>@item.Parent_Serial_Number</td>
                <td>
                    @Html.ActionLink("Edit", "PatientEdit", new { id = item.Patient_ID, CustId = item.Customer_ID }) |
                    @Html.ActionLink("Details", "PatientDetails", new { id = item.Patient_ID, CustId = item.Customer_ID })
                </td>
            }
        </tr>
    </table>
</div>*@

<p style="padding-top:40px">
    <hr />
</p>

<p style="padding-top:40px">
    
       
        @Html.ActionLink("Back to List", "PatientsIndex")
   
</p>

DeviceTrackingSystem/Views/Patients/Edit.cshtml
@model DeviceTrackingSystem.Models.Patient
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">


<h2>Edit Patient</h2>
<p style="font-size:19px">Edit Patient: @Html.DisplayTextFor(model=>model.Patient_ID)</p>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <table>
        <tr>
            <td colspan="2">
                @Html.HiddenFor(model => model.ID)
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                @Html.LabelFor(model => model.Customer_Name)
            </td>
            <td>
                @Html.DropDownList("Customer_ID", ViewBag.customerName as SelectList, " - Select - ", htmlAttributes: new { style = "width:400px" })
                @Html.ValidationMessageFor(model => model.Customer_Name)
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                @Html.LabelFor(model => model.Implant_Date)
            </td>
            <td>
             @Html.TextBoxFor(m => m.Implant_Date, "{0:dd/MM/yyyy}", new { @class = "datepicker" })                          
         
                @Html.ValidationMessageFor(model => model.Implant_Date)
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                @Html.LabelFor(model => model.Implant_Physcian)
            </td>
            <td>
                @Html.EditorFor(model => model.Implant_Physcian)
                @Html.ValidationMessageFor(model => model.Implant_Physcian)
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                @Html.LabelFor(model => model.Explant_Date )
             
            </td>
            <td>
                @Html.TextBoxFor(m => m.Explant_Date, new { @class = "datepicker" })       
               
                @Html.ValidationMessageFor(model => model.Explant_Date)
            </td>       
       </tr>
       
        <tr>

            <td></td>
            <td>
                <input type="submit" value="Save" style="width:60px" />
               
            </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Back to List", "PatientsIndex") 
     
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

<script>
    $(function () {
        $(".datepicker").datepicker({
            inline: true,
            showOtherMonths: true,
            dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
            dateformat: 'dd/mm/yyyy',
        });

    });
</script>






 


}









 
    

DeviceTrackingSystem/Views/Patients/PatientDetailsEdit.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelPateintDetails

@{
    ViewBag.Title = "PatientDetailsEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Patient Details Edit</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <table>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Part ID :
            </td>
            <td>                
                @Html.DropDownList("ID", ViewBag.partId as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Serial Number :
            </td>
            <td>
                @Html.DropDownList("ID", ViewBag.serialNumber as SelectList, " - Select - ", new { @class = "ddlDevice" })                
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Status :
            </td>
            <td>
                @Html.DropDownList("ID", ViewBag.status as SelectList, " - Select - ", new { @class = "ddlDevice" })                
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Parent Part ID :
            </td>
            <td>
                @Html.DropDownList("ID", ViewBag.parentPartID as SelectList, " - Select - ", new { @class = "ddlDevice" })                
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Parent Serial Number :
            </td>
            <td>
                @Html.DropDownList("ID", ViewBag.parentSerialNumber as SelectList, " - Select - ", new { @class = "ddlDevice" })                
            </td>
        </tr>
        <tr>
            <td></td>
            <td style="padding-top:20px"><input type="submit" value="Save" style="width:80px; height:30px"/></td>
        </tr>
    </table>    
}
<p style="padding-top:30px">
    <hr />
</p>
<div>
    @Html.ActionLink("Back to List", "Details", new { id = (int)@ViewBag.patientId, CustId = (string)@ViewBag.custID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<style type="text/css">
    .ddlDevice {
        Width: 120px;
        height: 25px;
    }
</style>

DeviceTrackingSystem/Views/Patients/PatientSubDetails.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelPateintDetails

@{
    ViewBag.Title = "PatientSubDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Patient Details</h2>
<hr />

<table class="table table-striped">
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Part ID :
        </td>
        <td>
            @ViewBag.id
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Serial Number :
        </td>
        <td>
            @ViewBag.serialNumber
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Status :
        </td>
        <td>
            @ViewBag.status
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Parent Part ID :
        </td>
        <td >
            @ViewBag.parentPartID
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Parent Serial Number :
        </td>
        <td >
            @ViewBag.parentSerialNumber
        </td>
    </tr>
</table>
<hr />

@Html.ActionLink("Back to List", "Details", new { id = (int)@ViewBag.id, CustId = (string)@ViewBag.custID })

DeviceTrackingSystem/Views/Patients/PatientsIndex.cshtml
@model IEnumerable<DataAcessLayer.DeviceAccess>

@{
    ViewBag.Title = "PatientsIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebGrid grid = new WebGrid(
       Model,
       rowsPerPage: ViewBag.rowsPerPage,
       selectionFieldName: "selectedRow",
       ajaxUpdateContainerId: "gridContent"
   );
}

<h3>Patients Index</h3>

@using (Html.BeginForm("PatientsIndex", "Patients", FormMethod.Get))
{
    <div style="padding-left:750px" id="divMessage">
        <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
    </div>
    
    <div>
        <table>
            <tr>
                <td >
                    @Html.Label("Find by PatientID:", null, new { @class = "cssPartID" })
                </td>
                <td >
                    @Html.TextBox("SearchKey", "", new { @class = "csstxtSearch" })
                </td>
                <td>
                    <input type="submit" value="Search" id="btnSubmit" />
                </td>
                <td>
                    @Html.ActionLink("Clear", "PatientsIndex", "Patients")
                </td>
                <td style="width:50px"></td>
               
                <td >
                    @Html.Label("Find by Customer:", null, new { @class = "cssParentPartID" })
                </td>
                <td >
                    @Html.TextBox("ParentSearchKey", "", new { @class = "csstxtSearch" })
                </td>
                <td>
                    <input type="submit" value="Search" id="btnSubmit" />
                </td>
                <td>
                    @Html.ActionLink("Clear", "PatientsIndex", "Patients")
                </td>
                <td style="width:50px"></td>
                <td>
                    @Html.Label("Find by Implant Date:", null, new { @class = "cssParentPartID" })
                </td>
                <td>
                    @Html.TextBox("ParentKey", "", new { @class = "csstxtSearch" })
                </td>
                <td>
                    <input type="submit" value="Search" id="btnSubmit" />
                </td>
                <td>
                    @Html.ActionLink("Clear", "PatientsIndex", "Patients")
                </td>
                
            </tr>
        </table>


    </div>

    <div style="float:right">
        <table>
            <tr style="float:left">
                <td style="width:60px;">
                    @Html.ActionLink("Show All", "PatientsIndex", new { ShowAll = "true" })
                </td>

                <td style="width:20px"></td>

                <td>
                    @Html.ActionLink("Show Archived", "PatientsIndex", "Patients")
                </td>
            </tr>
        </table>
    </div>

    <div id="gridContent">
        @grid.Table(

         htmlAttributes: new
            {
                id = "grid",
                @class = "table table-striped table-hover table-condensed"
            },
        alternatingRowStyle: "",
        selectedRowStyle: "",
        columns:
            grid.Columns(
                    grid.Column(columnName: "PatientID", header: "Patient ID"),
                    grid.Column(columnName: "Customer_Name", header: "Customer Name"),
                    grid.Column(columnName: "PatientsImplantPhysician", header: "IRF"),
                    grid.Column(columnName: "PatientsImplantDate", header: "Implant Date"),
                     grid.Column(columnName: "ImplantPhysician", header: "Implant Physician"),
                     grid.Column(columnName: "PatientsDeathDate", header: "Explant Date"),

                    grid.Column("", format: @<text>

                       @Html.ActionLink("Edit", "Edit", new { id = item.ID, CustId = item.Customer_ID }) |
                       @Html.ActionLink("Details", "Details", new { id = item.ID, CustId = item.Customer_ID }) |
                     
                       @Html.ActionLink("Delete", "DeletePatientRecord", new { id = item.ID }, new { onclick = "return confirm('Are you sure want to delete record ?');" })

                    </text>, style: "col2Width", canSort: false)
                                                                                                                                                                                                                             ))
    </div>

    <div class="pagination">
        <table>
            <tr>
                <td>
                    <ul>
                        <li>@grid.Pager(mode: WebGridPagerModes.All)</li>
                    </ul>
                </td>
                <td style="width:700px"></td>

                <td> Records Per Page:&nbsp;@Html.DropDownList("paging", new SelectList(new List<int> { 20, 50 }, ViewBag.rowsPerPage), new { @style = "width: 50px;", onchange = @"form.submit();" })</td>
            </tr>
        </table>

    </div>

    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
    </script>

}