DeviceTrackingSystem/Models/Device.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Device
    {
        public Device()
        {
            this.Device_Locations = new HashSet<Device_Locations>();
        }
    
        public int ID { get; set; }

        [StringLength(25, ErrorMessage = "Valid Only 25 Characters")]
        [RegularExpression("^([a-zA-Z0-9 .&'-_]+)$", ErrorMessage = "Invalid Part_ID")]
        [Required(ErrorMessage = "Please Enter Part_ID")]
        public string Part_ID { get; set; }

        [StringLength(25, ErrorMessage = "Valid Only 25 Characters")]
        [RegularExpression("^([a-zA-Z0-9 .&'-_]+)$", ErrorMessage = "Invalid Serial Number")]
        [Required(ErrorMessage = "Please Enter  Serial Number")]
        public string Serial_Number { get; set; }
        [Required(ErrorMessage = "Please Enter Serial Number")]
        public string ParentSerialNumber { get; set; }
        [Required(ErrorMessage = "Please Enter Customer")]
        public string Customer_Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public bool Archived { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public string Last_Updated_By { get; set; }
    
        public virtual ICollection<Device_Locations> Device_Locations { get; set; }
    }
}

DeviceTrackingSystem/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAcessLayer;
using System.Data.SqlClient;
using System.Data;
using System.Web.UI.WebControls;
using System.Web.Security;
using DeviceTrackingSystem.Models;
using System.Net;

namespace DeviceTrackingSystem.Controllers
{
    public class DeviceController : Controller
    {
        DeviceTrackingEntities db = new DeviceTrackingEntities();
        DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
        [HttpGet]
        // GET: /Device/
        [Authorize]
        public ActionResult DeviceIndex(string paging)
        {
            if (!String.IsNullOrEmpty(paging))
            {                
                ViewBag.rowsPerPage = int.Parse(paging);
            }
            else
            {
                // default value
                ViewBag.rowsPerPage = 20;
            }
            DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
            List<DeviceAccess> lstDevice = deviceDataAcessLayer.DeviceData.ToList();
            if (HttpContext.Request.QueryString.Count == 0 || HttpContext.Request.QueryString.Count > 0)
            {
                string showAll = string.Empty;
                if (HttpContext.Request.QueryString["ShowAll"] != null)
                    showAll = HttpContext.Request.QueryString["ShowAll"].ToString().Trim();
                if (showAll == "true")
                {
                    lstDevice = deviceDataAcessLayer.DeviceData.ToList();
                }
                else if (showAll == "false")
                {
                    lstDevice = deviceDataAcessLayer.DeviceData.Where(d => d.Archived == true).ToList();
                }
                else
                {
                    lstDevice = deviceDataAcessLayer.DeviceData.Where(d => d.Archived == false).ToList();
                }
            }
            if (HttpContext.Request.QueryString.Count > 0)
            {
                string SearchKey = string.Empty;
                if (HttpContext.Request.QueryString["SearchKey"] != null)
                    SearchKey = HttpContext.Request.QueryString["SearchKey"].ToString().Trim();
                string ParentSearchKey = string.Empty;
                if (HttpContext.Request.QueryString["ParentSearchKey"] != null)
                    ParentSearchKey = HttpContext.Request.QueryString["ParentSearchKey"].ToString().Trim();
                if (!string.IsNullOrEmpty(SearchKey) && string.IsNullOrEmpty(ParentSearchKey))
                {
                    lstDevice = lstDevice.Where(i => i.Part_ID.Contains(SearchKey) || i.Serial_Number.Contains(SearchKey)).ToList();
                }
                else if (string.IsNullOrEmpty(SearchKey) && !string.IsNullOrEmpty(ParentSearchKey))
                {
                    lstDevice = lstDevice.Where(i => i.Parent_ID.Contains(ParentSearchKey) || i.ParentSerialNumber.Contains(ParentSearchKey)).ToList();
                }
                else if (!string.IsNullOrEmpty(SearchKey) && !string.IsNullOrEmpty(ParentSearchKey))
                {
                    lstDevice = lstDevice.Where(i => i.Part_ID.Contains(SearchKey) || i.Serial_Number.Contains(SearchKey) || i.Parent_ID.Contains(ParentSearchKey) || i.ParentSerialNumber.Contains(ParentSearchKey)).ToList();
                }
            }
            return View(lstDevice);

          
        }        

        //
        // GET: /Device/Details/5
        //[Authorize]
        //public ActionResult Details(int id)
        //{
        //    DeviceDataAcessLayer objDetails = new DeviceDataAcessLayer();
        //    //Device device = objDetails.Device.FirstOrDefault(emp => emp.ID == id);
        //    DeviceAccess device = objDetails.DeviceData.FirstOrDefault(emp => emp.ID == id);
        //    return View(device);
        //}
        [Authorize(Roles = "ReadWrite")]
        public ActionResult Details(int id = 0)
        {
            DataAcessLayer.DeviceAccess.ViewModelDeviceDetails objviewModeldeviceDetails = new DataAcessLayer.DeviceAccess.ViewModelDeviceDetails();
            objviewModeldeviceDetails.deviceDetails = deviceDataAcessLayer.DeviceDetailDAL().Where(d => d.ID == id).ToList();
            objviewModeldeviceDetails.deviceParentDetails = deviceDataAcessLayer.DeviceParentDetailsDAL().Where(d => d.ID == id).ToList();
            objviewModeldeviceDetails.deviceLocationHistoryDetails = deviceDataAcessLayer.DeviceLocationHistoryDetailsDAL().Where(d => d.DeviceID == id).ToList();
            //objviewModeldeviceDetails.deviceChildDetails = deviceDataAcessLayer.DeviceChildDetailsDAL().Where(d => d.ID == id).ToList();
            objviewModeldeviceDetails.deviceChildDetails = deviceDataAcessLayer.DeviceSubChildDetailsDAL(id).ToList();
           return View(objviewModeldeviceDetails);
        }        

        //
        // GET: /Device/Create
           [Authorize(Roles = "ReadWrite")]
        public ActionResult Create()
        {
            // Class1 dbconnection = new Class1();
            DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
            List<DataAcessLayer.DeviceAccess.DeviceDetails> pcontent = new List<DeviceAccess.DeviceDetails>();
            {
                //Get all page content from TblHome table
                pcontent = deviceDataAcessLayer.DeviceDetailDAL();

            };
            List<SelectListItem> DeviceList = new List<SelectListItem>();          
            foreach (var item in pcontent)
            {
                DeviceList.Add(new SelectListItem
                {
                    Text = item.PartID,
                    Value = item.ID.ToString()
                });
            }

            ViewBag.NameList = DeviceList;
            return View();     
        }

        //
        // POST: /Device/Create
        [Authorize(Roles = "ReadWrite")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                string Part_ID = Request.Form["Part_ID"];
                string Serial_Number = Request.Form["Serial_Number"];
                string Status = Request.Form["StatusDropDown"];
                int Parent_ID = Convert.ToInt32(Request.Form["ID"]);               

                string updatedby = User.Identity.Name;
                if (ModelState.IsValid)
                {
                    DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
                    bool isSaved = deviceLayer.SaveDevicesDetails(Part_ID, Serial_Number, Status, Parent_ID, updatedby);
                    if (isSaved)
                    {
                        TempData["message"] = "Record Successfully Saved";

                    }
                    else
                    {
                        TempData["message"] = "Record Not Saved";
                    }

                }
                return RedirectToAction("Create");

            }
            catch
            {
                return View();
            }
        }

        public ActionResult CreateDeviceLocation()
        {
            // Class1 dbconnection = new Class1();
            DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
            List<DataAcessLayer.DeviceAccess.DeviceDetails> pcontent = new List<DeviceAccess.DeviceDetails>();
            {
                //Get all page content from TblHome table
                pcontent = deviceDataAcessLayer.DeviceDetailDAL();

            };
            List<SelectListItem> DeviceList = new List<SelectListItem>();
            foreach (var item in pcontent)
            {
                DeviceList.Add(new SelectListItem
                {
                    Text = item.PartID,
                    Value = item.ID.ToString()
                });
            }

            ViewBag.NameList = DeviceList;

            List<DataAcessLayer.DeviceAccess.Customers> pcontent1 = new List<DeviceAccess.Customers>();
            {
                //Get all page content from TblHome table
                pcontent1 = deviceDataAcessLayer.CustomersListDAL();

            };
            List<SelectListItem> CustomersList = new List<SelectListItem>();
            foreach (var item in pcontent1)
            {
                CustomersList.Add(new SelectListItem
                {
                    Text = item.CustomerName,
                    Value = item.CustomerID.ToString()
                });
            }

            ViewBag.CustomerList = CustomersList;
            return View();
        }

        [Authorize(Roles = "ReadWrite")]
        [HttpPost]
        public ActionResult CreateDeviceLocation(FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                int Device_ID = Convert.ToInt32(Request.Form["ID"]);
                int Customer_ID = Convert.ToInt32(Request.Form["CustomerID"]);             
                string SO_ID = Request.Form["SO_ID"];
                string CurrentLoc = Request.Form["StatusDropDown"];

                string updatedby = User.Identity.Name;
                if (ModelState.IsValid)
                {
                    DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
                    bool isSaved = deviceLayer.SaveDeviceLocationDetails(Device_ID, Customer_ID, SO_ID, CurrentLoc, updatedby);
                    if (isSaved)
                    {
                        TempData["message"] = "Record Successfully Saved";

                    }
                    else
                    {
                        TempData["message"] = "Record Not Saved";
                    }

                }
                return RedirectToAction("CreateDeviceLocation");

            }
            catch
            {
                return View();
            }
        }

DeviceTrackingSystem/Views/Device/Create.cshtml
@model DeviceTrackingSystem.Models.Device
@{
    ViewBag.Title = " Create New Device";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create New Device</h2>
<style type="text/css">
    .validation-error {
        color: red;
        font-weight:100;
    }
</style>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div style="padding-left:750px" id="divMessage">
        <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
    </div>

    <table style="font-size:16px">
        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Part_ID)
            </td>
            <td>
                @Html.EditorFor(model => model.Part_ID)
              
                @Html.ValidationMessageFor(m => m.Part_ID, null, new { @class = "validation-error", data_valmsg_for = "Part_ID" })
            </td>
            <td style="padding-left:20px;font-size:small;font-family:Arial;font-style:italic">ex:M10202.</td>
        </tr>

        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Serial_Number)
            </td>
            <td>
                @Html.EditorFor(model => model.Serial_Number)
               
                @Html.ValidationMessageFor(m => m.Serial_Number, null, new { @class = "validation-error", data_valmsg_for = "Serial_Number" })
            </td>
            <td style="padding-left:20px;font-size:small;font-family:Arial;font-style:italic">ex:SK-P0134.</td>
        </tr>

        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Status)
            </td>
            <td>
               @Html.DropDownList("StatusDropDown", new List<SelectListItem>
                {                 
                    
                    new SelectListItem{ Text="Available", Value = "available" },
                    new SelectListItem{ Text="In use", Value = "in use" },
                    new SelectListItem{ Text="Service", Value = "service" }
                 })
              
            </td>          
        </tr>

        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Parent_ID)
            </td>
            <td>
                @Html.DropDownList("ID", (IEnumerable<SelectListItem>)ViewBag.NameList, "Select Parent Part_ID")              
                @Html.ValidationMessageFor(model => model.Parent_ID)
            </td>
        </tr>

        

        <tr>
            <td style="padding-top:60px"></td>
            <td>
                <input type="submit" value="Save" style="width:60px" />
            </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Back to List", "DeviceIndex")
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeviceTrackingSystem/Views/Device/CreateDeviceLocation.cshtml
@model DeviceTrackingSystem.Models.Device_Locations
@{
    ViewBag.Title = " Create New Device Location";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create New Device Location</h2>

<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div style="padding-left:750px" id="divMessage">
        <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
    </div>

    <table style="font-size:16px">
        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Device_ID)
            </td>
            <td>
                @Html.DropDownList("ID", (IEnumerable<SelectListItem>)ViewBag.NameList, "Select Device_ID")
                @Html.ValidationMessageFor(model => model.Device_ID)
            </td>
        </tr>

        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Customer_ID)
            </td>
            <td>
                @Html.DropDownList("CustomerID", (IEnumerable<SelectListItem>)ViewBag.CustomerList, "Select Customer")
                @Html.ValidationMessageFor(model => model.Customer_ID)
            </td>
        </tr>


        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.SO_ID)
            </td>
            <td>
                @Html.EditorFor(model => model.SO_ID)
                @Html.ValidationMessageFor(model => model.SO_ID)
            </td>
           
        </tr>

        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Current_Location)
            </td>
            <td>
                @Html.DropDownList("StatusDropDown", new List<SelectListItem>
                {
                    new SelectListItem{ Text="True", Value = "True" },
                    new SelectListItem{ Text="False", Value = "False" },
                })

            </td>
        </tr>

       



        <tr>
            <td style="padding-top:60px"></td>
            <td>
                <input type="submit" value="Save" style="width:60px" />
            </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Back to List", "DeviceIndex")
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeviceTrackingSystem/Views/Device/Details.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelDeviceDetails

@{
    ViewBag.Title = " Device Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<h2>Device Details</h2>
<div style="padding-left:750px" id="divMessage">
    <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
</script>
<hr />
<style type="text/css">
    .EditListColor {
        color: lightblue;
    }
</style>

@foreach (var item in Model.deviceDetails)
{
    <table>
        <tr>
            <td align="right" style="font-weight:600; font-size:15px">Part ID :</td>
            <td>@item.PartID</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:600; font-size:15px">Serial Number :</td>
            <td>@item.SerialNumber</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:600; font-size:15px">Status :</td>
            <td>@item.Status</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:600; font-size:15px">Parent Part ID :</td>
            <td>@item.ParentPartID</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:600; font-size:15px">Parent Serial Number :</td>
            <td>@item.ParentSerialNumber</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:600; font-size:15px">Updated :</td>
            <td>@item.Updated</td>
        </tr>
        <tr>
            <td align="right" style="font-weight:600; font-size:15px">Last Updated By :</td>
            <td>@item.LastUpdatedBy</td>
        </tr>
    </table>
}
<p style="padding-top:10px"></p>
<hr />
<p style="font-size:21px; font-weight:500">
    Parent Device
</p>
<hr />
@if (Model.deviceParentDetails.Count > 0)
{
    
   
    <div style="padding-left:10px">
        <table class="table table-striped">
            <tr>               
                <td align="right" style="font-weight:700; font-size:16px; padding-left:30px">Parent Part ID</td>
                <td align="right" style="font-weight:700; font-size:16px; padding-left:30px">Parent Serial Number</td>
                <td></td>
            </tr>
            @foreach (var item in Model.deviceParentDetails)
            {
                 <tr>
                    <td style="padding-left:30px">@item.ParentPartID</td>
                    <td style="padding-left:30px">@item.ParentSerialNumber</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID, CustId = item.Customer_ID, DeviceLocId = item.DeviceLocationId, Status = item.Status, ParentID = item.ParentPartID, Pid = item.PID, ParentpartId = item.ParentPartID, psn = item.ParentSerialNumber }, new { target = "_blank" }) |

                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ID, CustId = item.Customer_ID, DeviceLocId = item.DeviceLocationId, Status = item.Status, ParentID = item.Parent_ID, Pid = item.PID }) |*@
                        @Html.ActionLink("Details", "Details", new { id = item.PID }, new { target = "_blank" })
                
                     </td>
                </tr>
            }
        </table>
    </div>
}
else
{
    <hr />
    <div style="padding-left:400px; padding-top:20px; padding-bottom:20px">
        <h3>No parent for this device</h3>
    </div>
    <hr />
}


<hr />
<p style="font-size:21px; font-weight:500">
    Device Location History
</p>
<hr />
@if (Model.deviceLocationHistoryDetails.Count > 0)
{

<div style="padding-left:10px">
    <table class="table table-striped">
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">Customer Name</td>
            <td align="right" style="font-weight:700; font-size:16px; padding-left:30px">Sales Order ID</td>
            <td align="left" style="font-weight:700; font-size:16px; padding-left:30px">Date</td>
            <td></td>
        </tr>
        @foreach (var item in Model.deviceLocationHistoryDetails)
        {
            <tr>
                <td>@item.CustomerName</td>
                <td style="padding-left:30px">@item.SalesOrderID</td>
                <td style="padding-left:30px">@item.DeviceLocDate</td>
                <td>
                    @Html.ActionLink("Edit", "DeviceLocationHistoryDetailsEdit", new { id = item.ID, CustId = item.ID, deviceId = item.DeviceID }) |
                    @Html.ActionLink("Details", "DeviceLocationHistoryDetails", new { deviceID = item.DeviceID, customerName = item.CustomerName, salesOrderID = item.SalesOrderID, deviceLocDate = item.DeviceLocDate })
              
                </td>
            </tr>
        }
    </table>
</div>
}
else
{
    <hr />
    <div style="padding-left:400px; padding-top:20px; padding-bottom:20px">
        <h3>No Device Location for this device</h3>
    </div>
    <hr />
}
<hr />

<p style="font-size:21px; font-weight:500">
    Child Devices
</p>
<hr />
@if (Model.deviceChildDetails.Count > 0)
{

   

    <div style="padding-left:10px">
        <table class="table table-striped">
            <tr>
                <td align="right" style="font-weight:700; font-size:16px">Part ID</td>
                <td align="right" style="font-weight:700; font-size:16px; padding-left:30px">Serial Number</td>
                <td align="right" style="font-weight:700; font-size:16px; padding-left:30px">Status</td>
                <td align="right" style="font-weight:700; font-size:16px; padding-left:30px">Parent Part ID</td>
                <td align="right" style="font-weight:700; font-size:16px; padding-left:30px">Parent Serial Number</td>
                <td></td>
            </tr>
            @foreach (var item in Model.deviceChildDetails)
            {
                <tr>
                    <td>@item.PartID</td>
                    <td style="padding-left:30px">@item.SerialNumber</td>
                    <td style="padding-left:30px">@item.Status</td>
                    <td style="padding-left:30px">@item.ParentPartID</td>
                    <td style="padding-left:30px">@item.ParentSerialNumber</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID, CustId = item.Customer_ID, DeviceLocId = item.DeviceLocationId, Status = item.Status, ParentID = item.ParentPartID, Pid = item.PID, ParentpartId = item.ParentPartID, psn = item.ParentSerialNumber }, new { target = "_blank" }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }, new { target = "_blank" })
                    </td>
                </tr>
            }
        </table>
    </div>
}
else
{
     <hr />
    <div style="padding-left:400px; padding-top:20px; padding-bottom:20px">
        <h3>No child devices for this device</h3>
    </div>
    <hr />
    <hr />
}

<p style="color:lightblue">   
    @Html.ActionLink("Back to List", "DeviceIndex")
</p>

DeviceTrackingSystem/Views/Device/DeviceIndex.cshtml
@model IEnumerable<DataAcessLayer.DeviceAccess>
    @{ 
       
    ViewBag.Title = "DeviceIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebGrid grid = new WebGrid(
       Model,rowsPerPage: ViewBag.rowsPerPage,   
    selectionFieldName: "selectedRow",
    canPage: true,
    ajaxUpdateContainerId: "gridContent"
    );
}

    <h3>DeviceIndex</h3>


@using (Html.BeginForm("DeviceIndex", "Device", FormMethod.Get))
{
    <div style="padding-left:750px" id="divMessage">
        <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
    </div>
        <div>

            <table>
                <tr>
                    <td>
                        @Html.Label("Find by PartID or Serial Number:", null, new { @class = "cssPartID" })
                    </td>
                    <td>
                        @Html.TextBox("SearchKey", "", new { @class = "csstxtSearch" })
                    </td>
                    <td>
                        <input type="submit" value="Search" id="btnSubmit" />
                    </td>
                    <td>
                        @Html.ActionLink("Clear", "DeviceIndex", "Device")
                    </td>
                    <td style="width:50px"></td>
                    <td>
                        @Html.Label("Find by Parent Part ID or Patient Serial Number", null, new { @class = "cssParentPartID" })
                    </td>
                    <td>
                        @Html.TextBox("ParentSearchKey", "", new { @class = "csstxtSearch" })
                    </td>
                    <td>
                        <input type="submit" value="Search" id="btnSubmit" />
                    </td>
                    <td>

                        @Html.ActionLink("Clear", "DeviceIndex", "Device")
                    </td>
                </tr>
            </table>


        </div>

    <div style="float:right">
        <table>
            <tr style="float:left">
                <td style="width:70px;">
                    @Html.ActionLink("Show All", "DeviceIndex", new { ShowAll = "true" })
               </td>
                <td style="width:20px"></td>
                <td>
                    @Html.ActionLink("Show Archived", "DeviceIndex", new { ShowAll = "false" })
                </td>
            </tr>
        </table>
    </div>
        <div id="gridContent">
            @grid.Table(

         htmlAttributes: new
            {
                id = "grid",

                @class = "table table-striped table-hover table-condensed"
            },
        alternatingRowStyle: "",
        selectedRowStyle: "",
           
            columns: grid.Columns(

                    grid.Column(columnName: "Part_ID", header: "Part ID"),
                    grid.Column(columnName: "Serial_Number", header: "Serial Number"),
                    grid.Column(columnName: "Status", header: "Status"),
                    grid.Column(columnName: "Parent_ID", header: "Parent Part ID"),                   
                    grid.Column(columnName: "ParentSerialNumber", header: "Parent Serial Number"),
                    grid.Column(columnName: "Customer_Name", header: "Customer Name"),

                    grid.Column("", format: @<text>
           
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID, CustId = item.Customer_ID, DeviceLocId = item.DeviceLocationId, Status = item.Status, ParentID = item.Parent_ID, Pid = item.PID, ParentpartId = item.Parent_ID, psn = item.ParentSerialNumber }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                      
                        @Html.ActionLink("Delete", "DeleteDevice", new { id = item.ID }, new { onclick = "return confirm('Are you sure want to delete record ?');" })

                    </text>, style: "col3Width", canSort: false)
                                                                                                                                         ))
        </div>
    
        <div class="pagination">
            <table>
                <tr>
                    <td>
                        <ul>
                            <li>@grid.Pager(mode: WebGridPagerModes.All)</li>
                        </ul>
                    </td>
                    <td style="width:700px"></td>

                    <td> Records Per Page:&nbsp;@Html.DropDownList("paging", new SelectList(new List<int> { 20, 50 }, ViewBag.rowsPerPage), new { @style = "width: 50px;", onchange = @"form.submit();" })</td>
                </tr>
            </table>                     
          
</div>

   

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
    </script>
}

    





    