DeviceTrackingSystem/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public int ID { get; set; }
        [StringLength(8, ErrorMessage = "Valid Only Eight Characters")]
        [RegularExpression("^([a-zA-Z0-9 .&'-_]+)$", ErrorMessage = "Invalid Customer_ID")]
        [Required(ErrorMessage = "Please Enter Customer_ID")]
        public string Customer_ID { get; set; }
        public int Account_ID { get; set; }

        [StringLength(255, ErrorMessage = "Valid Only 255 Characters")]
        [RegularExpression("^([a-zA-Z0-9 .&'-_]+)$", ErrorMessage = "Invalid Customer Name")]
        [Required(ErrorMessage = "Please Enter Customer Name")]
        public string Customer_Name { get; set; }
        public bool Archived { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public string Last_Updated_By { get; set; }
    
        public virtual SF_Accounts SF_Accounts { get; set; }
    }
}

DeviceTrackingSystem/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAcessLayer;
using System.Data.SqlClient;
using System.Data;
using System.Web.UI.WebControls;
using System.Web.Security;
using DeviceTrackingSystem.Models;
using System.Net;

namespace DeviceTrackingSystem.Controllers
{
    public class CustomersController : Controller
    {
        DeviceTrackingEntities db = new DeviceTrackingEntities();
        DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
        [HttpGet]
        // GET: /Customers/
        [Authorize]
        public ActionResult CustomersIndex(string paging)
        {
            if (!String.IsNullOrEmpty(paging))
            {
                ViewBag.rowsPerPage = int.Parse(paging);
            }
            else
            {
                // default value
                ViewBag.rowsPerPage = 20;
            }
            DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
            List<DeviceAccess> lstLog = deviceDataAcessLayer.CustomerDevice.ToList();
            if (HttpContext.Request.QueryString.Count == 0 || HttpContext.Request.QueryString.Count > 0)
            {
                string showAll = string.Empty;
                if (HttpContext.Request.QueryString["ShowAll"] != null)
                    showAll = HttpContext.Request.QueryString["ShowAll"].ToString().Trim();
                if (showAll == "true")
                {
                    lstLog = deviceDataAcessLayer.CustomerDevice.ToList();
                }
                else if(showAll == "false")
                {
                    lstLog = deviceDataAcessLayer.CustomerDevice.Where(c => c.Archived == true).ToList();
                }
                else
                {
                    lstLog = deviceDataAcessLayer.CustomerDevice.Where(c => c.Archived == false).ToList();
                }
            }
            if (HttpContext.Request.QueryString.Count > 0)
            {
                string SearchKey = string.Empty;
                if (HttpContext.Request.QueryString["SearchKey"] != null)
                    SearchKey = HttpContext.Request.QueryString["SearchKey"].ToString().Trim();
                if (!string.IsNullOrEmpty(SearchKey))
                {
                    lstLog = lstLog.Where(i => i.ExpandableCustomerID.Contains(SearchKey) || i.ExpandableCustomerName.Contains(SearchKey)).ToList();
                }
                
            }

            return View(lstLog);
        }

        //
        // GET: /Customers/Details/5

        //
        // GET: /Customers/Details/5
        [Authorize(Roles = "ReadWrite")]
        public ActionResult Details(int id = 0, int Pid = 0)
        {
            DataAcessLayer.DeviceAccess.ViewModelCustomerDetails objviewModelCustomerDetails = new DataAcessLayer.DeviceAccess.ViewModelCustomerDetails();
            objviewModelCustomerDetails.customersDetails = deviceDataAcessLayer.CustomerDetails(id).ToList();
            objviewModelCustomerDetails.customersDetailsDevice = deviceDataAcessLayer.CustomerDetailsDevices().Where(c => c.ID == id || c.PID == Pid).ToList();
            objviewModelCustomerDetails.customersDetailsPatient = deviceDataAcessLayer.CustomerDetailsPateints().Where(c => c.Customer_Id == id).ToList();


            return View(objviewModelCustomerDetails);
        }

        //
        // GET: /Customers/Create
        [Authorize(Roles = "ReadWrite")]
        public ActionResult Create()
        {

           // Class1 dbconnection = new Class1();
            DeviceDataAcessLayer deviceDataAcessLayer = new DeviceDataAcessLayer();
            List<DataAcessLayer.SFAccounts> pcontent = new List<DataAcessLayer.SFAccounts>();
            {
                //Get all page content from TblHome table
                pcontent = deviceDataAcessLayer.SF_AccountsDAL();

            };
            List<SelectListItem> accountList = new List<SelectListItem>();
            //List<string> items = new List<string>();
            foreach (var item in pcontent)
            {
                accountList.Add(new SelectListItem
                {
                    Text = item.Account_Name,
                    Value = item.ID.ToString()
                });
            }

            ViewBag.AccountNameList = accountList;
            return View();         
        }

        //
        // POST: /Customers/Create

        [Authorize(Roles = "ReadWrite")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                
                string Customer_ID = Request.Form["Customer_ID"];
                int AccountID =Convert.ToInt32(Request.Form["ID"]);
                string Customer_Name = Request.Form["Customer_Name"];

                string updatedby = User.Identity.Name;
                if (ModelState.IsValid)
                {
                    DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
                    bool isSaved = deviceLayer.SaveCustomerDetails(Customer_ID, AccountID, Customer_Name, updatedby);
                    if (isSaved)
                    {
                        TempData["message"] = "Record Successfully Saved";
                        //return RedirectToAction("CustomersIndex");
                    }
                    else
                    {
                        TempData["message"] = "Record Not Saved";
                       // return RedirectToAction("CustomersIndex");
                    }

                }
               return RedirectToAction("Create");

            }
            catch
            {
                return View();
            }
        }

       
        

        //
        // POST: /Customers/Edit/5
        [Authorize(Roles = "ReadWrite")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, int CustId = 0)
        {
            try
            {
                // TODO: Add update logic here

                string ID = Request.Form["ID"];
                var newID = ID.Split(',')[1];
                int AccountId = Convert.ToInt32(newID);
                int CustomerID = Convert.ToInt32(CustId);
                var updatedby = User.Identity.Name;


                string archived = Request.Form["templateId"];
                int a = archived.IndexOf(",");
                string archivednew = (a >= 0) ? archived.Substring(0, a) : archived;

                if (ModelState.IsValid)
                {
                    DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
                    bool isUpdated = deviceLayer.SaveCustomers(AccountId, CustomerID, updatedby, archivednew);
                    if (isUpdated)
                    {
                        TempData["message"] = "Record Successfully Updated";
                        return RedirectToAction("CustomersIndex");
                    }
                    {
                        TempData["message"] = "Error Occured!!";
                        return RedirectToAction("CustomersIndex");
                    }

                }
                return RedirectToAction("CustomersIndex");

            }
            catch
            {
                return View();
            }
        }
        [Authorize(Roles = "ReadWrite")]
        public ActionResult Edit(int id = 0, string Customer_Name = "", string customerCode = "", int CustId = 0)
        {
            SF_Accounts sfaccounts = new SF_Accounts();
          
            DeviceAccess device = new DeviceAccess();
            DeviceDataAcessLayer customer = new DeviceDataAcessLayer();
            if (customer == null)
            {
                return HttpNotFound();
            }
            sfaccounts = db.SF_Accounts.Find(id);
            ViewBag.sfAccountName = new SelectList(db.SF_Accounts.OrderBy(y => y.Account_Name), "ID", "Account_Name", id);
            bool IsArchived = customer.GetIsArchived(CustId, id);
            ViewBag.Isarchived = IsArchived;
            TempData["IsArchived"] = IsArchived;
            TempData["customerName"] = Customer_Name;
            TempData["customerID"] = customerCode;
            return View(sfaccounts);
        }
        //
        // GET: /Customers/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View();
        }
        [Authorize(Roles = "ReadWrite")]
        public ActionResult CustomersDelete(string id = "")
        {
            if (ModelState.IsValid)
            {
                DeviceDataAcessLayer deviceLayer = new DeviceDataAcessLayer();
                var updatedby = User.Identity.Name;
                bool IsDeleted = deviceLayer.DeleteCustomerRecord(id, updatedby);
                if (IsDeleted)
                {
                    TempData["message"] = "Record Successfully Deleted";
                }
                return RedirectToAction("CustomersIndex");
            }
            return View();
        }
        //
        // POST: /Customers/Delete/5
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "ReadWrite")]
        public ActionResult CustomerDetailsDeviceDetails(int id = 0, string partID = "", string serialNumber = "", string status = "", string parentPartID = "", string parentSerialNumber = "")
        {

            ViewBag.id = id;
            ViewBag.partID = partID.ToString();
            ViewBag.serialNumber = serialNumber.ToString();
            ViewBag.status = status.ToString();
            ViewBag.parentPartID = parentPartID.ToString();

DeviceTrackingSystem/Views/Customers/Create.cshtml
@model DeviceTrackingSystem.Models.Customer



@{
    
    ViewBag.Title = " Create New Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h2>Create New Customer</h2>

<hr />
<style type="text/css">
.validation-error {

    color:red;
     font-weight:100;
}
    </style>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div style="padding-left:750px" id="divMessage">
        <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
    </div>

<table style="font-size:16px">
        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Customer_ID) 
            </td>
            <td>
                @Html.EditorFor(model => model.Customer_ID)
              
                @Html.ValidationMessageFor(m => m.Customer_ID, null, new { @class= "validation-error", data_valmsg_for = "Customer_ID" })
            </td>
            <td style="padding-left:20px;font-size:small;font-family:Arial;font-style:italic">ex:Z-MNI.</td>
        </tr>
        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.SF_Accounts.Account_ID)
            </td>
            <td>
                @Html.DropDownList("ID", (IEnumerable<SelectListItem>)ViewBag.AccountNameList, "Select Account Name")
              @*@Html.DropDownListFor(M => M.SF_Accounts, new SelectList("Account_ID", "Account_Name"))*@ 
              @Html.ValidationMessageFor(model => model.SF_Accounts.Account_ID)
            </td>
        </tr>
        <tr>
            <td align="left" style="font-weight:bold; font-size:16px;">
                @Html.LabelFor(model => model.Customer_Name)
            </td>
            <td>
                @Html.EditorFor(model => model.Customer_Name)
                @Html.ValidationMessageFor(model => model.Customer_Name, null, new { @class = "validation-error", data_valmsg_for = "Customer_Name" })
            </td>
        </tr>


  

        <tr>
            <td style="padding-top:60px"></td>
            <td>
                <input type="submit" value="Save" style="width:60px" />
            </td>
        </tr>
    </table>


    
}

<div>
    @Html.ActionLink("Back to List", "CustomersIndex")
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


    

DeviceTrackingSystem/Views/Customers/CustomerDetailsDeviceDetails.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelCustomerDetails

@{
    ViewBag.Title = "CustomerDetailsDeviceDetails";
}

<h2>Customer Device Details</h2>

    <hr />

<table class ="table table-striped">
    <tr>
        <td align="right" style="font-weight:700; font-size:16px; padding-top:20px">
            Part ID :
        </td>
        <td >
            @ViewBag.partID
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Serial Number :
        </td>
        <td >
            @ViewBag.serialNumber
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Status :
        </td>
        <td >
            @ViewBag.status
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Parent Part ID :
        </td>
        <td >
            @ViewBag.parentPartID
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Parent Serial Number :
        </td>
        <td >
            @ViewBag.parentSerialNumber
        </td>
    </tr>
    </table>
    <p style="padding-top:30px">
        <hr />
    </p>
    <p>
        @*@Html.ActionLink("Edit", "Edit" ) |*@
        @Html.ActionLink("Back to List", "Details", new { id = (int)ViewBag.id })
    </p>

DeviceTrackingSystem/Views/Customers/CustomerDetailsDeviceEdit.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelCustomerDetails

@{
    ViewBag.Title = "CustomerDetailsDeviceEdit";
}

<h2>Customer Device Edit</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <table>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Part ID :
            </td>
            <td>
                @Html.DropDownList("PID", ViewBag.partID as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Serial Number :
            </td>
            <td>
                @Html.DropDownList("PID", ViewBag.serialNumber as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Status :
            </td>
            <td>
                @Html.DropDownList("PID", ViewBag.status as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Parent Part ID :
            </td>
            <td>
                @Html.DropDownList("PID", ViewBag.parentPartID as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Parent Serial Number :
            </td>
            <td>
                @Html.DropDownList("PID", ViewBag.parentSerialNumber as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Save" style="width:80px; height:30px" /></td>
        </tr>
    </table>
}
<hr />
<div>
    @Html.ActionLink("Back to List", "Details", new { id = (int)ViewBag.id })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<style type="text/css">
    .ddlDevice {
        Width: 120px;
        height: 25px;
    }
</style>

DeviceTrackingSystem/Views/Customers/CustomerDetailsPatientDetails.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelCustomerDetails

@{
    ViewBag.Title = "CustomerDetailsPatientDetails";
}

<h2>Customer Patient Details</h2>
<hr />

<table class="table table-striped">
    <tr>
        <td align="right" style="font-weight:700; font-size:16px; padding-top:20px">
            Patient ID :
        </td>
        <td ">
            @ViewBag.patientID
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            IRF :
        </td>
        <td >
            @ViewBag.iRF
        </td>
    </tr>
    <tr>
        <td align="right" style="font-weight:700; font-size:16px">
            Implant Date :
        </td>
        <td >
            @ViewBag.implantDate
        </td>
    </tr>
</table>
<p style="padding-top:30px">
    <hr />
</p>
<p>
    @*@Html.ActionLink("Edit", "Edit") |*@
    @Html.ActionLink("Back to List", "Details", new { id = (int)ViewBag.customerID })
</p>

DeviceTrackingSystem/Views/Customers/CustomerDetailsPatientEdit.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelCustomerDetails

@{
    ViewBag.Title = "CustomerDetailsPatientEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Customer Patient Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <p style="padding-top:1px"></p>
    <table>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Patient ID :
            </td>
            <td>
                @Html.DropDownList("ID", ViewBag.patientID as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                IRF :
            </td>
            <td>
                @Html.DropDownList("ID", ViewBag.iRF as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">
                Implant Date :
            </td>
            <td>
                @Html.DropDownList("ID", ViewBag.implantDate as SelectList, " - Select - ", new { @class = "ddlDevice" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td style="padding-top:20px"><input type="submit" value="Save" style="width:80px; height:30px" /></td>
        </tr>
    </table>

}
<p style="padding-top:30px">
    <hr />
</p>
<div>
    @Html.ActionLink("Back to List", "Details", new { id = (int)ViewBag.customerID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeviceTrackingSystem/Views/Customers/CustomersIndex.cshtml
@model IEnumerable<DataAcessLayer.DeviceAccess>

@{
    ViewBag.Title = "CustomersIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";

    WebGrid grid = new WebGrid(
        Model,
        rowsPerPage: ViewBag.rowsPerPage,
        selectionFieldName: "selectedRow",
        ajaxUpdateContainerId: "gridContent"
    );
}

<h3>Customer Index</h3>
@using (Html.BeginForm("CustomersIndex", "Customers", FormMethod.Get))
{
    <div style="padding-left:750px" id="divMessage">
        <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
    </div>
    <div>
        <table>
            <tr>
                <td>
                    @Html.Label("Find by CustomerID or Name:", null, new { @class = "cssPartID" })
                </td>
                <td>
                    @Html.TextBox("SearchKey", "", new { @class = "csstxtSearch" })
                </td>
                <td>
                    <input type="submit" value="Search" id="btnSubmit" />
                </td>

                <td>
                    @Html.ActionLink("Clear",  "CustomersIndex","Customers")
                    
                  
                </td>
            </tr>
        </table>
    </div>
    <div style="float:right">
        <table>
            <tr style="float:left">
                <td style="width:80px;">
                    @Html.ActionLink("Show All", "CustomersIndex", new { ShowAll = "true" })
                <td>
                    @Html.ActionLink("Show Archived", "CustomersIndex", new { ShowAll = "false" })
                </td>
                <td style="width:50px"></td>
            </tr>
        </table>
    </div>
    <div id="gridContent">
        @grid.Table(

         htmlAttributes: new
            {
                id = "grid",
                @class = "table table-striped table-hover table-condensed"
            },
        alternatingRowStyle: "",
        selectedRowStyle: "",
        columns: grid.Columns(

             grid.Column(columnName: "ExpandableCustomerID", header: "Expandable CustomerID"),
             grid.Column(columnName: "ExpandableCustomerName", header: "Expandable Customer Name"),
             grid.Column(columnName: "SalesForceCustomerName", header: "Sales Force Customer Name"),

             grid.Column("", format: @<text>

               @Html.ActionLink("Edit", "Edit", new { id = item.SF_AccountID, Customer_Name = item.ExpandableCustomerName, customerCode = item.ExpandableCustomerID, CustId = item.ID }) |      
               @Html.ActionLink("Details", "Details", new { id = item.ID }) |           
               @Html.ActionLink("Delete", "CustomersDelete", new { id = item.ExpandableCustomerID }, new { onclick = "return confirm('Are you sure want to delete record ?');" })
            </text>, style: "col2Width", canSort: false)




                                                                                                                                                                                                                                                         ))
    </div>
    <div class="pagination">
        <table style="width:100%;height:100px">
            <tr>
                <td >
                    <ul class="pagination">
                        <li>@grid.Pager(mode: WebGridPagerModes.All)</li>
                    </ul>
                </td>
               </tr>
           </table>
      

    </div>
    <div style="width:100%"><table>
    <tr>

        <td style="padding-left:900px;width:1000px"> Records Per Page:&nbsp;@Html.DropDownList("paging", new SelectList(new List<int> { 20, 50 }, ViewBag.rowsPerPage), new { @style = "width: 50px;", onchange = @"form.submit();" })</td>
    </tr>
</table></div>

    

   

    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
    </script>

}

DeviceTrackingSystem/Views/Customers/Details.cshtml
@model DataAcessLayer.DeviceAccess.ViewModelCustomerDetails

@{
    ViewBag.Title = "CustomerDetails";
}

<h2>Customer Information Details</h2>

<hr />
<div style="padding-left:750px" id="divMessage">
    <p style="color:red; width:250px; font-size:large">@TempData["message"]</p>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#divMessage").fadeOut(5000);
    });
</script>
@foreach (var item in Model.customersDetails)
{
    <table >
        <tr> <td style="font-weight:600; font-size:15px">Customer ID :</td>
            <td align="left">@item.CustomerID</td>
        </tr>
        <tr>
            <td style="font-weight:600; font-size:15px">Customer Name :</td>
            <td>@item.CustomerName</td>
        </tr>
        <tr>
            <td style="font-weight:600; font-size:15px">SalesForce Account  :</td>
            <td>@item.SalesForceAccount</td>
        </tr>
        <tr>
            <td style="font-weight:600; font-size:15px">Updated  :</td>
            <td>@item.Updated</td>
        </tr>
        <tr>
            <td style="font-weight:600; font-size:15px">Updated by  :</td>
            <td>@item.LastAlteredBy</td>
        </tr>
    </table>
}
@if (Model.customersDetailsDevice.Count > 0)
{

    <p style="padding-top:30px"><hr /></p>
    <h2 >Devices</h2>
    <hr />

    <table class="table table-striped">
        <tr>
            <td align="right" style="font-weight:700; font-size:16px">Part ID</td>
            <td align="right" style="font-weight:700; font-size:16px">Serial Number</td>
            <td align="right" style="font-weight:700; font-size:16px">Status</td>
            <td align="right" style="font-weight:700; font-size:16px">Parent Part ID</td>
            <td align="right" style="font-weight:700; font-size:16px">Parent Serial Number</td>
            <td></td>
        </tr>
        @foreach (var item in Model.customersDetailsDevice)
        {
            <tr>
                <td style="padding-right:20px">@item.PartID</td>
                <td style="padding-right:20px">@item.SerialNumber</td>
                <td style="padding-right:20px">@item.Status</td>
                <td style="padding-right:20px">@item.ParentPartID</td>
                <td style="padding-right:20px">@item.ParentSerialNumber</td>
                <td>
                  
                     @Html.ActionLink("Edit", "Edit", "Device", new { id = item.PID, CustId = item.CustID, DeviceLocId = item.DeviceLocId, Status = item.Status, ParentID = item.ParentPartID, Pid = item.PID, ParentpartId = item.ParentPartID, psn = item.ParentSerialNumber }, new { target = "_blank" }) |

                    @Html.ActionLink("Details", "Details", "Device", new { id = item.PID },new { target = "_blank" })
                </td>
            </tr>
        }
    </table>
}
else
{
    <hr />
    <div style="padding-left:400px; padding-top:20px; padding-bottom:20px">
        <h3>No devices for this customer</h3>
    </div>
    <hr />
}


@if (Model.customersDetailsPatient.Count > 0)
{

    <p style="padding-top:30px"><hr /></p>
    <h2 style="font-weight:600">Patients</h2>
    <hr />

    <table class="table table-striped">
        <tr>
            <td align="center" style="font-weight:700; font-size:16px">Patient ID</td>
            <td align="center" style="font-weight:700; font-size:16px">IRF</td>
            <td align="center" style="font-weight:700; font-size:16px">Implant Date</td>
            <td></td>
        </tr>
        @foreach (var item in Model.customersDetailsPatient)
        {
            <tr>
                <td>@item.PatientID</td>
                <td>@item.IRF</td>
                <td>@item.ImplantDate</td>
                <td>
                    @Html.ActionLink("Edit", "CustomerDetailsPatientEdit", new { id = item.ID, customerID = item.Customer_Id }, new { target = "_blank" }) | 
                    @Html.ActionLink("Details", "CustomerDetailsPatientDetails", new { id = item.ID, patientID = item.PatientID, iRF = item.IRF, implantDate = item.ImplantDate, customerID = item.Customer_Id }, new { target = "_blank" })
                </td>
            </tr>
        }
    </table>
}
else
{
    <hr />
    <div style="padding-left:400px; padding-top:20px; padding-bottom:20px">
        <h3>No Patients for this customer</h3>
    </div>
    <hr />
}



    <div style="padding-top:50px">
        
        @Html.ActionLink("Back to List", "CustomersIndex")
        </div>
<p style="padding-top:30px"><hr /></p>